.TH INDI-BACKUP 1 "August 12, 2015"
.SH NAME
indi-backup \- A modular backup system write in bash with minimal dependency.
.SH SYNOPSIS
.B indi-backup
.RI [ options ] " tasks ..."
.PP
.SH CONFIGURATION
The default configuration file is /etc/indi-backup.conf
.TP
The complete configuration documentation is availabale at
.BR https://github.com/indigen-solutions/indi-backup/wiki
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-version
Print the version and exit
.TP
.B \-c, \-\-config
Overide the default config file location.
.TP
.B \-\-list\-tasks
List all available tasks
.TP
.B \-\-list\-storages
List all available storages
.SH AUTHOR
.br
Jérôme Quéré <jerome.quere@indigen.com>
