#!/bin/bash
################################################################################
#
# The MIT License (MIT)
#
# Copyright (c) 2015 Indigen-Solution
# See the AUTHORS file for details.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
################################################################################

################################################################################
# This is the main indi-backup script
################################################################################

#
# Load libraries
#

IB_LIB_DIR="/usr/lib/indi-backup"

if [ ! -z $IB_DEVEL ]
then
    IB_LIB_DIR="./lib"
fi

source $IB_LIB_DIR/utils.sh

source $IB_LIB_DIR/task.sh
source $IB_LIB_DIR/tasks/docker-mysql-dumper.sh
source $IB_LIB_DIR/tasks/mysql.sh
source $IB_LIB_DIR/tasks/subtask.sh
source $IB_LIB_DIR/tasks/tarball.sh
source $IB_LIB_DIR/tasks/tarball-incremental.sh

source $IB_LIB_DIR/storage.sh
source $IB_LIB_DIR/storages/fs.sh
source $IB_LIB_DIR/storages/ssh.sh
source $IB_LIB_DIR/storages/swift.sh


#
# Set default variables
#
VERSION="@@VERSION@@"
CONFIG_FILE="/etc/indi-backup.conf"
TASKS=""
DATE=$(date --utc "+%Y%m%dT%H%M%SZ")

IB_OPTIONS_LIST_TASKS=""
IB_OPTIONS_LIST_STORAGES=""

#
# Parse command line arguments
#
while [[ $# > 0 ]]
do
    key="$1"
    case $key in
	-c|--config)
	    CONFIG_FILE="$2"
	    shift
	    ;;
	--list-tasks)
	    IB_OPTIONS_LIST_TASKS=1
	    ;;
	--list-storages)
	    IB_OPTIONS_LIST_STORAGES=1
	    ;;
	-h|--help)
	    ib_print_usage
	    exit 0
	    ;;
	--version)
	    echo "Version: $VERSION"
	    exit 0
	    ;;
	-*)
	    echo "Unknow options $1"
	    exit -1
	    ;;
	*)
	    TASKS="$TASKS $1"
	    ;;
    esac
    shift
done

#
# Include config file and do some check
#
if [[ (! -f $CONFIG_FILE)  || (! -r $CONFIG_FILE) ]]
then
    echo "No valid config file found [$CONFIG_FILE]";
    exit -1;
fi

source $CONFIG_FILE

if [ -z "$IB_TASKS" ]
then
    echo "Invalid IB_TASKS in config file"
    exit -1;
fi

if [ -z "$IB_STORAGES" ]
then
    echo "Invalid IB_STORAGES in config file"
    exit -1;
fi

#
# Run options
#
if [ ! -z "$IB_OPTIONS_LIST_TASKS" ]
then
    ib_task_list
fi

if [ ! -z "$IB_OPTIONS_LIST_STORAGES" ]
then
    ib_storage_list
fi

#
# Run task
#
error=0
for task in $TASKS
do
    ib_task_run $task || error=1
done

exit $error
